//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiquiBaseRelease) DeepCopyInto(out *LiquiBaseRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiquiBaseRelease.
func (in *LiquiBaseRelease) DeepCopy() *LiquiBaseRelease {
	if in == nil {
		return nil
	}
	out := new(LiquiBaseRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiquiBaseRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiquiBaseReleaseList) DeepCopyInto(out *LiquiBaseReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiquiBaseRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiquiBaseReleaseList.
func (in *LiquiBaseReleaseList) DeepCopy() *LiquiBaseReleaseList {
	if in == nil {
		return nil
	}
	out := new(LiquiBaseReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiquiBaseReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiquiBaseReleaseSpec) DeepCopyInto(out *LiquiBaseReleaseSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiquiBaseReleaseSpec.
func (in *LiquiBaseReleaseSpec) DeepCopy() *LiquiBaseReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(LiquiBaseReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiquiBaseReleaseStatus) DeepCopyInto(out *LiquiBaseReleaseStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiquiBaseReleaseStatus.
func (in *LiquiBaseReleaseStatus) DeepCopy() *LiquiBaseReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(LiquiBaseReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiquiBaseRollback) DeepCopyInto(out *LiquiBaseRollback) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiquiBaseRollback.
func (in *LiquiBaseRollback) DeepCopy() *LiquiBaseRollback {
	if in == nil {
		return nil
	}
	out := new(LiquiBaseRollback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiquiBaseRollback) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiquiBaseRollbackList) DeepCopyInto(out *LiquiBaseRollbackList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LiquiBaseRollback, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiquiBaseRollbackList.
func (in *LiquiBaseRollbackList) DeepCopy() *LiquiBaseRollbackList {
	if in == nil {
		return nil
	}
	out := new(LiquiBaseRollbackList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LiquiBaseRollbackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiquiBaseRollbackSpec) DeepCopyInto(out *LiquiBaseRollbackSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiquiBaseRollbackSpec.
func (in *LiquiBaseRollbackSpec) DeepCopy() *LiquiBaseRollbackSpec {
	if in == nil {
		return nil
	}
	out := new(LiquiBaseRollbackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiquiBaseRollbackStatus) DeepCopyInto(out *LiquiBaseRollbackStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiquiBaseRollbackStatus.
func (in *LiquiBaseRollbackStatus) DeepCopy() *LiquiBaseRollbackStatus {
	if in == nil {
		return nil
	}
	out := new(LiquiBaseRollbackStatus)
	in.DeepCopyInto(out)
	return out
}
